parameters:
  buildArchitecture: 'x64'
jobs:
- job: build_macOS_${{ parameters.buildArchitecture }}
  displayName: Build macOS ${{ parameters.buildArchitecture }}
  condition: succeeded()
  pool:
    type: linux
    isCustom: true
    name: Azure Pipelines
    vmImage: 'macOS-latest'

  variables:
  - name: HOMEBREW_NO_ANALYTICS
    value: 1
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - group: DotNetPrivateBuildAccess
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: PowerShellRoot
    value: $(Build.SourcesDirectory)

  steps:
  - checkout: self
    clean: true
    env:
      ob_restore_phase: true # This ensures checkout is done at the beginning of the restore phase

  - template: /.pipelines/templates/SetVersionVariables.yml@self
    parameters:
      ReleaseTagVar: $(ReleaseTagVar)
  - pwsh: |
      # create folder
      sudo mkdir "$(Agent.TempDirectory)/PowerShell"
      # make the current user the owner
      sudo chown $env:USER "$(Agent.TempDirectory)/PowerShell"
    displayName: 'Create $(Agent.TempDirectory)/PowerShell'

    ## We cross compile for arm64, so the arch is always x64
  - template: /.pipelines/templates/install-dotnet.yml@self

  - pwsh: |
      Import-Module $(PowerShellRoot)/build.psm1 -Force
      Start-PSBootstrap -Scenario Package
    displayName: 'Bootstrap VM'
    env:
      __DOTNET_RUNTIME_FEED_KEY: $(RUNTIME_SOURCEFEED_KEY)

  - template: /.pipelines/templates/insert-nuget-config-azfeed.yml@self
    parameters:
      repoRoot: $(PowerShellRoot)
  - pwsh: |
      $env:AzDevOpsFeedPAT2 = '$(powershellPackageReadPat)'
      # Add -SkipReleaseChecks as a mitigation to unblock release.
      # macos-10.15 does not allow creating a folder under root. Hence, moving the folder.

      Import-Module ./build.psm1 -Force

      $ReleaseTagParam = @{}

      if ($env:RELEASETAGVAR) {
        $ReleaseTagParam['ReleaseTag'] = $env:RELEASETAGVAR
      }

      Start-PSBuild -Runtime 'osx-${{ parameters.buildArchitecture }}' -Configuration Release -PSModuleRestore -Clean -Output $(OB_OUTPUTDIRECTORY) @ReleaseTagParam
      $artifactName = "macosBinResults-${{ parameters.buildArchitecture }}"

      $psOptPath = "$(OB_OUTPUTDIRECTORY)/psoptions.json"
      Save-PSOptions -PSOptionsPath $psOptPath

      # Since we are using custom pool for macOS, we need to use artifact.upload to publish the artifacts
      Write-Host "##vso[artifact.upload containerfolder=$artifactName;artifactname=$artifactName]$(OB_OUTPUTDIRECTORY)"

      $env:AzDevOpsFeedPAT2 = $null
    displayName: 'Build'
    env:
      __DOTNET_RUNTIME_FEED_KEY: $(RUNTIME_SOURCEFEED_KEY)

  - template: /.pipelines/templates/step/finalize.yml@self
