parameters:
  buildArchitecture: 'x64'
jobs:
- job: build_macOS_${{ parameters.buildArchitecture }}
  displayName: Build macOS ${{ parameters.buildArchitecture }}
  condition: succeeded()
  pool:
    type: linux
    isCustom: true
    name: Azure Pipelines
    vmImage: 'macOS-latest'

  variables:
  - name: HOMEBREW_NO_ANALYTICS
    value: 1
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - group: DotNetPrivateBuildAccess
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: PowerShellRoot
    value: $(Build.SourcesDirectory)

  steps:
  - checkout: self
    clean: true
    env:
      ob_restore_phase: true # This ensures checkout is done at the beginning of the restore phase

  - template: /.pipelines/templates/SetVersionVariables.yml@self
    parameters:
      ReleaseTagVar: $(ReleaseTagVar)
  - pwsh: |
      # create folder
      sudo mkdir "$(Agent.TempDirectory)/PowerShell"
      # make the current user the owner
      sudo chown $env:USER "$(Agent.TempDirectory)/PowerShell"
    displayName: 'Create $(Agent.TempDirectory)/PowerShell'

    ## We cross compile for arm64, so the arch is always x64
  - template: /.pipelines/templates/install-dotnet.yml@self

  - pwsh: |
      Import-Module $(PowerShellRoot)/build.psm1 -Force
      Start-PSBootstrap -Scenario Package
    displayName: 'Bootstrap VM'
    env:
      __DOTNET_RUNTIME_FEED_KEY: $(RUNTIME_SOURCEFEED_KEY)

  - template: /.pipelines/templates/insert-nuget-config-azfeed.yml@self
    parameters:
      repoRoot: $(PowerShellRoot)
  - pwsh: |
      $env:AzDevOpsFeedPAT2 = '$(powershellPackageReadPat)'
      # Add -SkipReleaseChecks as a mitigation to unblock release.
      # macos-10.15 does not allow creating a folder under root. Hence, moving the folder.

      Import-Module ./build.psm1 -Force

      $ReleaseTagParam = @{}

      if ($env:RELEASETAGVAR) {
        $ReleaseTagParam['ReleaseTag'] = $env:RELEASETAGVAR
      }

      Start-PSBuild -Runtime 'osx-${{ parameters.buildArchitecture }}' -Configuration Release -PSModuleRestore -Clean -Output $(OB_OUTPUTDIRECTORY) @ReleaseTagParam
      $artifactName = "macosBinResults-${{ parameters.buildArchitecture }}"

      $psOptPath = "$(OB_OUTPUTDIRECTORY)/psoptions.json"
      Save-PSOptions -PSOptionsPath $psOptPath

      # Since we are using custom pool for macOS, we need to use artifact.upload to publish the artifacts
      Write-Host "##vso[artifact.upload containerfolder=$artifactName;artifactname=$artifactName]$(OB_OUTPUTDIRECTORY)"

      $env:AzDevOpsFeedPAT2 = $null
    displayName: 'Build'
    env:
      __DOTNET_RUNTIME_FEED_KEY: $(RUNTIME_SOURCEFEED_KEY)

  - template: /.pipelines/templates/step/finalize.yml@self

- job: sign_${{ parameters.buildArchitecture }}
  displayName: Sign_macOS_${{ parameters.buildArchitecture }}
  condition: succeeded()
  dependsOn: build_macOS_${{ parameters.buildArchitecture }}
  pool:
    type: linux
    isCustom: true
    name: Azure Pipelines
    vmImage: 'macOS-latest'
  variables:
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: ob_signing_setup_enabled
    value: false
  - name: ob_sdl_codeSignValidation_enabled
    value: false
  - name: BuildArchitecture
    value: ${{ parameters.buildArchitecture }}
  - name: ob_sdl_codeql_compiled_enabled
    value: false
  - name: ob_sdl_sbom_packageName
    value: 'Microsoft.Powershell.MacOS.${{parameters.buildArchitecture}}'
  - group: mscodehub-macos-package-signing

  steps:
  - checkout: self
    clean: true

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: 'macosBinResults-$(BuildArchitecture)'
    displayName: Download build

  - pwsh: |
      Get-ChildItem "$(Pipeline.Workspace)/macosBinResults-$(BuildArchitecture)" -Recurse
    displayName: 'Capture Downloaded Artifacts'
    continueOnError: true

  - task: EsrpCodeSigning@5
    displayName: 'Apple Developer Sign and Harden macOS binaries'
    inputs:
      ConnectedServiceName: 'ESRPMacOSSigning'
      AppRegistrationClientId: '$(AppRegistrationClientId)'
      AppRegistrationTenantId: '$(AppRegistrationTenantId)'
      ServiceEndpointUrl: '$(ServiceEndpointUrl)'
      FolderPath: '$(Pipeline.Workspace)/macosBinResults-$(BuildArchitecture)'
      Pattern: '*.dll,*.dylib,pwsh'
      UseMinimatch: true
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
            "KeyCode": "CP-401337-Apple",
            "OperationCode": "MacAppDeveloperSign",
            "Parameters": {
              "Hardening": "--options=runtime"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
        ]
    retryCountOnTaskFailure: 2
    timeoutInMinutes: 15

  - pwsh: |
      $signedDir = New-Item -ItemType Directory -Path '$(ob_outputDirectory)/Signed-$(BuildArchitecture)' -Force
      Copy-Item -Path '$(Pipeline.Workspace)/macosBinResults-$(BuildArchitecture)/*' -Destination $signedDir -Recurse -Force
      Write-Verbose -Verbose "Signed files copied to $signedDir"
      Get-ChildItem $signedDir -Recurse | Select-Object -ExpandProperty FullName
    displayName: 'Copy signed files to output'

  - template: /.pipelines/templates/step/finalize.yml@self
